import { Container, Row, Col, Image } from "react-bootstrap";

import { AiFillHtml5 } from "react-icons/ai";
import { SiCss3, SiJavascript, SiReact, SiBootstrap } from "react-icons/si";

import { Link } from "react-router-dom";
function About() {
  return (
    <div>
      <Container className="p-5 ">
        <Row className="d-flex justify-content-evenly align-items-center">
          <Col lg={{ span: 3, offset: 1 }} className="text-center ">
            <Image
              src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Magic8ball.jpg/220px-Magic8ball.jpg"
              alt="8-magic-ball"
            />
          </Col>
          <Col lg={7}>
            <Row>
              <h1 className="text-white my-4">What is Magic 8-Ball</h1>
            </Row>
            <p className="text-white fs-5">
              The Magic 8-Ball is a plastic sphere, made to look like an
              eight-ball, that is used for fortune-telling or seeking advice. It
              was invented in 1950 by Albert C. Carter and Abe Bookman and is
              currently manufactured by Mattel. The user asks a yes–no question
              to the ball, then turns it over to reveal an answer in a window on
              the ball.
            </p>
          </Col>
        </Row>
        <Row className="mt-5  text-white">
          <h1 className="text-white mb-4"> About This Project </h1>
          <p className="fs-5">
            This is a small application that takes yes/no question from user and
            displays a random answer which is generated by an API.
          </p>
          <p>
            {" "}
            <Link
              to={"//www.yesno.wtf/"}
              target="_blank"
              className="text-decoration-none"
            >
              YesNo API{" "}
            </Link>
          </p>
        </Row>

        <Row className="text-white ">
          <h1 className="text-white  my-5"> Technologies </h1>
          <Col className="py-3">
            <AiFillHtml5 size={100} />
          </Col>
          <Col className="py-3">
            <SiCss3 size={100} />
          </Col>
          <Col className="py-3">
            <SiJavascript size={100} />
          </Col>
          <Col className="py-3">
            <SiReact size={100} />
          </Col>
          <Col className="py-3">
            <SiBootstrap size={100} />
          </Col>
        </Row>
      </Container>
    </div>
  );
}

export default About;
